// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0-devel
// 	protoc        v3.12.3
// source: drill_exercise_1/modulation/protobuf/modu.proto

package modupb

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Variable struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	First  int32 `protobuf:"varint,1,opt,name=first,proto3" json:"first,omitempty"`
	Second int32 `protobuf:"varint,2,opt,name=second,proto3" json:"second,omitempty"`
}

func (x *Variable) Reset() {
	*x = Variable{}
	if protoimpl.UnsafeEnabled {
		mi := &file_drill_exercise_1_modulation_protobuf_modu_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Variable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Variable) ProtoMessage() {}

func (x *Variable) ProtoReflect() protoreflect.Message {
	mi := &file_drill_exercise_1_modulation_protobuf_modu_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Variable.ProtoReflect.Descriptor instead.
func (*Variable) Descriptor() ([]byte, []int) {
	return file_drill_exercise_1_modulation_protobuf_modu_proto_rawDescGZIP(), []int{0}
}

func (x *Variable) GetFirst() int32 {
	if x != nil {
		return x.First
	}
	return 0
}

func (x *Variable) GetSecond() int32 {
	if x != nil {
		return x.Second
	}
	return 0
}

type ModRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Constant *Variable `protobuf:"bytes,1,opt,name=constant,proto3" json:"constant,omitempty"`
}

func (x *ModRequest) Reset() {
	*x = ModRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_drill_exercise_1_modulation_protobuf_modu_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModRequest) ProtoMessage() {}

func (x *ModRequest) ProtoReflect() protoreflect.Message {
	mi := &file_drill_exercise_1_modulation_protobuf_modu_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModRequest.ProtoReflect.Descriptor instead.
func (*ModRequest) Descriptor() ([]byte, []int) {
	return file_drill_exercise_1_modulation_protobuf_modu_proto_rawDescGZIP(), []int{1}
}

func (x *ModRequest) GetConstant() *Variable {
	if x != nil {
		return x.Constant
	}
	return nil
}

type ModResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *ModResponse) Reset() {
	*x = ModResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_drill_exercise_1_modulation_protobuf_modu_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModResponse) ProtoMessage() {}

func (x *ModResponse) ProtoReflect() protoreflect.Message {
	mi := &file_drill_exercise_1_modulation_protobuf_modu_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModResponse.ProtoReflect.Descriptor instead.
func (*ModResponse) Descriptor() ([]byte, []int) {
	return file_drill_exercise_1_modulation_protobuf_modu_proto_rawDescGZIP(), []int{2}
}

func (x *ModResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_drill_exercise_1_modulation_protobuf_modu_proto protoreflect.FileDescriptor

var file_drill_exercise_1_modulation_protobuf_modu_proto_rawDesc = []byte{
	0x0a, 0x2f, 0x64, 0x72, 0x69, 0x6c, 0x6c, 0x5f, 0x65, 0x78, 0x65, 0x72, 0x63, 0x69, 0x73, 0x65,
	0x5f, 0x31, 0x2f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x6d, 0x6f, 0x64, 0x75, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x06, 0x6d, 0x6f, 0x64, 0x75, 0x70, 0x62, 0x22, 0x38, 0x0a, 0x08, 0x56, 0x61, 0x72,
	0x69, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x69, 0x72, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x66, 0x69, 0x72, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x65, 0x63, 0x6f, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x65, 0x63,
	0x6f, 0x6e, 0x64, 0x22, 0x3a, 0x0a, 0x0a, 0x4d, 0x6f, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x2c, 0x0a, 0x08, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x6f, 0x64, 0x75, 0x70, 0x62, 0x2e, 0x56, 0x61, 0x72,
	0x69, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x22,
	0x25, 0x0a, 0x0b, 0x4d, 0x6f, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0x43, 0x0a, 0x0a, 0x4d, 0x6f, 0x64, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x35, 0x0a, 0x0a, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x12, 0x2e, 0x6d, 0x6f, 0x64, 0x75, 0x70, 0x62, 0x2e, 0x4d, 0x6f, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x6d, 0x6f, 0x64, 0x75, 0x70, 0x62, 0x2e,
	0x4d, 0x6f, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2d, 0x5a, 0x2b, 0x64,
	0x72, 0x69, 0x6c, 0x6c, 0x5f, 0x65, 0x78, 0x65, 0x72, 0x63, 0x69, 0x73, 0x65, 0x5f, 0x31, 0x2f,
	0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x3b, 0x6d, 0x6f, 0x64, 0x75, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_drill_exercise_1_modulation_protobuf_modu_proto_rawDescOnce sync.Once
	file_drill_exercise_1_modulation_protobuf_modu_proto_rawDescData = file_drill_exercise_1_modulation_protobuf_modu_proto_rawDesc
)

func file_drill_exercise_1_modulation_protobuf_modu_proto_rawDescGZIP() []byte {
	file_drill_exercise_1_modulation_protobuf_modu_proto_rawDescOnce.Do(func() {
		file_drill_exercise_1_modulation_protobuf_modu_proto_rawDescData = protoimpl.X.CompressGZIP(file_drill_exercise_1_modulation_protobuf_modu_proto_rawDescData)
	})
	return file_drill_exercise_1_modulation_protobuf_modu_proto_rawDescData
}

var file_drill_exercise_1_modulation_protobuf_modu_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_drill_exercise_1_modulation_protobuf_modu_proto_goTypes = []interface{}{
	(*Variable)(nil),    // 0: modupb.Variable
	(*ModRequest)(nil),  // 1: modupb.ModRequest
	(*ModResponse)(nil), // 2: modupb.ModResponse
}
var file_drill_exercise_1_modulation_protobuf_modu_proto_depIdxs = []int32{
	0, // 0: modupb.ModRequest.constant:type_name -> modupb.Variable
	1, // 1: modupb.ModService.Modulation:input_type -> modupb.ModRequest
	2, // 2: modupb.ModService.Modulation:output_type -> modupb.ModResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_drill_exercise_1_modulation_protobuf_modu_proto_init() }
func file_drill_exercise_1_modulation_protobuf_modu_proto_init() {
	if File_drill_exercise_1_modulation_protobuf_modu_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_drill_exercise_1_modulation_protobuf_modu_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Variable); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_drill_exercise_1_modulation_protobuf_modu_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_drill_exercise_1_modulation_protobuf_modu_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_drill_exercise_1_modulation_protobuf_modu_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_drill_exercise_1_modulation_protobuf_modu_proto_goTypes,
		DependencyIndexes: file_drill_exercise_1_modulation_protobuf_modu_proto_depIdxs,
		MessageInfos:      file_drill_exercise_1_modulation_protobuf_modu_proto_msgTypes,
	}.Build()
	File_drill_exercise_1_modulation_protobuf_modu_proto = out.File
	file_drill_exercise_1_modulation_protobuf_modu_proto_rawDesc = nil
	file_drill_exercise_1_modulation_protobuf_modu_proto_goTypes = nil
	file_drill_exercise_1_modulation_protobuf_modu_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ModServiceClient is the client API for ModService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ModServiceClient interface {
	Modulation(ctx context.Context, in *ModRequest, opts ...grpc.CallOption) (*ModResponse, error)
}

type modServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewModServiceClient(cc grpc.ClientConnInterface) ModServiceClient {
	return &modServiceClient{cc}
}

func (c *modServiceClient) Modulation(ctx context.Context, in *ModRequest, opts ...grpc.CallOption) (*ModResponse, error) {
	out := new(ModResponse)
	err := c.cc.Invoke(ctx, "/modupb.ModService/Modulation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ModServiceServer is the server API for ModService service.
type ModServiceServer interface {
	Modulation(context.Context, *ModRequest) (*ModResponse, error)
}

// UnimplementedModServiceServer can be embedded to have forward compatible implementations.
type UnimplementedModServiceServer struct {
}

func (*UnimplementedModServiceServer) Modulation(context.Context, *ModRequest) (*ModResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Modulation not implemented")
}

func RegisterModServiceServer(s *grpc.Server, srv ModServiceServer) {
	s.RegisterService(&_ModService_serviceDesc, srv)
}

func _ModService_Modulation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModServiceServer).Modulation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/modupb.ModService/Modulation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModServiceServer).Modulation(ctx, req.(*ModRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ModService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "modupb.ModService",
	HandlerType: (*ModServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Modulation",
			Handler:    _ModService_Modulation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "drill_exercise_1/modulation/protobuf/modu.proto",
}
