// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0-devel
// 	protoc        v3.12.3
// source: drill_exercise_1/filter/protobuf/filter.proto

package filterpb

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Number struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num int32 `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *Number) Reset() {
	*x = Number{}
	if protoimpl.UnsafeEnabled {
		mi := &file_drill_exercise_1_filter_protobuf_filter_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Number) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Number) ProtoMessage() {}

func (x *Number) ProtoReflect() protoreflect.Message {
	mi := &file_drill_exercise_1_filter_protobuf_filter_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Number.ProtoReflect.Descriptor instead.
func (*Number) Descriptor() ([]byte, []int) {
	return file_drill_exercise_1_filter_protobuf_filter_proto_rawDescGZIP(), []int{0}
}

func (x *Number) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

type FilterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *Number `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *FilterRequest) Reset() {
	*x = FilterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_drill_exercise_1_filter_protobuf_filter_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterRequest) ProtoMessage() {}

func (x *FilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_drill_exercise_1_filter_protobuf_filter_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterRequest.ProtoReflect.Descriptor instead.
func (*FilterRequest) Descriptor() ([]byte, []int) {
	return file_drill_exercise_1_filter_protobuf_filter_proto_rawDescGZIP(), []int{1}
}

func (x *FilterRequest) GetData() *Number {
	if x != nil {
		return x.Data
	}
	return nil
}

type FilterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result bool `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *FilterResponse) Reset() {
	*x = FilterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_drill_exercise_1_filter_protobuf_filter_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FilterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterResponse) ProtoMessage() {}

func (x *FilterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_drill_exercise_1_filter_protobuf_filter_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterResponse.ProtoReflect.Descriptor instead.
func (*FilterResponse) Descriptor() ([]byte, []int) {
	return file_drill_exercise_1_filter_protobuf_filter_proto_rawDescGZIP(), []int{2}
}

func (x *FilterResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

var File_drill_exercise_1_filter_protobuf_filter_proto protoreflect.FileDescriptor

var file_drill_exercise_1_filter_protobuf_filter_proto_rawDesc = []byte{
	0x0a, 0x2d, 0x64, 0x72, 0x69, 0x6c, 0x6c, 0x5f, 0x65, 0x78, 0x65, 0x72, 0x63, 0x69, 0x73, 0x65,
	0x5f, 0x31, 0x2f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x08, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x70, 0x62, 0x22, 0x1a, 0x0a, 0x06, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x6e, 0x75, 0x6d, 0x22, 0x35, 0x0a, 0x0d, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x70, 0x62, 0x2e,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x28, 0x0a, 0x0e,
	0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0x52, 0x0a, 0x0d, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x41, 0x0a, 0x0c, 0x46, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x17, 0x2e, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x70, 0x62, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x18, 0x2e, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x70, 0x62, 0x2e, 0x46, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2d, 0x5a, 0x2b, 0x2e, 0x2f,
	0x64, 0x72, 0x69, 0x6c, 0x6c, 0x5f, 0x65, 0x78, 0x65, 0x72, 0x63, 0x69, 0x73, 0x65, 0x5f, 0x31,
	0x2f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x3b, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_drill_exercise_1_filter_protobuf_filter_proto_rawDescOnce sync.Once
	file_drill_exercise_1_filter_protobuf_filter_proto_rawDescData = file_drill_exercise_1_filter_protobuf_filter_proto_rawDesc
)

func file_drill_exercise_1_filter_protobuf_filter_proto_rawDescGZIP() []byte {
	file_drill_exercise_1_filter_protobuf_filter_proto_rawDescOnce.Do(func() {
		file_drill_exercise_1_filter_protobuf_filter_proto_rawDescData = protoimpl.X.CompressGZIP(file_drill_exercise_1_filter_protobuf_filter_proto_rawDescData)
	})
	return file_drill_exercise_1_filter_protobuf_filter_proto_rawDescData
}

var file_drill_exercise_1_filter_protobuf_filter_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_drill_exercise_1_filter_protobuf_filter_proto_goTypes = []interface{}{
	(*Number)(nil),         // 0: filterpb.Number
	(*FilterRequest)(nil),  // 1: filterpb.FilterRequest
	(*FilterResponse)(nil), // 2: filterpb.FilterResponse
}
var file_drill_exercise_1_filter_protobuf_filter_proto_depIdxs = []int32{
	0, // 0: filterpb.FilterRequest.data:type_name -> filterpb.Number
	1, // 1: filterpb.FilterService.FilterMethod:input_type -> filterpb.FilterRequest
	2, // 2: filterpb.FilterService.FilterMethod:output_type -> filterpb.FilterResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_drill_exercise_1_filter_protobuf_filter_proto_init() }
func file_drill_exercise_1_filter_protobuf_filter_proto_init() {
	if File_drill_exercise_1_filter_protobuf_filter_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_drill_exercise_1_filter_protobuf_filter_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Number); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_drill_exercise_1_filter_protobuf_filter_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FilterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_drill_exercise_1_filter_protobuf_filter_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FilterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_drill_exercise_1_filter_protobuf_filter_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_drill_exercise_1_filter_protobuf_filter_proto_goTypes,
		DependencyIndexes: file_drill_exercise_1_filter_protobuf_filter_proto_depIdxs,
		MessageInfos:      file_drill_exercise_1_filter_protobuf_filter_proto_msgTypes,
	}.Build()
	File_drill_exercise_1_filter_protobuf_filter_proto = out.File
	file_drill_exercise_1_filter_protobuf_filter_proto_rawDesc = nil
	file_drill_exercise_1_filter_protobuf_filter_proto_goTypes = nil
	file_drill_exercise_1_filter_protobuf_filter_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// FilterServiceClient is the client API for FilterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FilterServiceClient interface {
	FilterMethod(ctx context.Context, in *FilterRequest, opts ...grpc.CallOption) (*FilterResponse, error)
}

type filterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFilterServiceClient(cc grpc.ClientConnInterface) FilterServiceClient {
	return &filterServiceClient{cc}
}

func (c *filterServiceClient) FilterMethod(ctx context.Context, in *FilterRequest, opts ...grpc.CallOption) (*FilterResponse, error) {
	out := new(FilterResponse)
	err := c.cc.Invoke(ctx, "/filterpb.FilterService/FilterMethod", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FilterServiceServer is the server API for FilterService service.
type FilterServiceServer interface {
	FilterMethod(context.Context, *FilterRequest) (*FilterResponse, error)
}

// UnimplementedFilterServiceServer can be embedded to have forward compatible implementations.
type UnimplementedFilterServiceServer struct {
}

func (*UnimplementedFilterServiceServer) FilterMethod(context.Context, *FilterRequest) (*FilterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FilterMethod not implemented")
}

func RegisterFilterServiceServer(s *grpc.Server, srv FilterServiceServer) {
	s.RegisterService(&_FilterService_serviceDesc, srv)
}

func _FilterService_FilterMethod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FilterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilterServiceServer).FilterMethod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/filterpb.FilterService/FilterMethod",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilterServiceServer).FilterMethod(ctx, req.(*FilterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FilterService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "filterpb.FilterService",
	HandlerType: (*FilterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FilterMethod",
			Handler:    _FilterService_FilterMethod_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "drill_exercise_1/filter/protobuf/filter.proto",
}
