// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0-devel
// 	protoc        v3.12.3
// source: drill_exercise_1/division/protobuf/div.proto

package divpb

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Number struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	First  int32 `protobuf:"varint,1,opt,name=first,proto3" json:"first,omitempty"`
	Second int32 `protobuf:"varint,2,opt,name=second,proto3" json:"second,omitempty"`
}

func (x *Number) Reset() {
	*x = Number{}
	if protoimpl.UnsafeEnabled {
		mi := &file_drill_exercise_1_division_protobuf_div_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Number) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Number) ProtoMessage() {}

func (x *Number) ProtoReflect() protoreflect.Message {
	mi := &file_drill_exercise_1_division_protobuf_div_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Number.ProtoReflect.Descriptor instead.
func (*Number) Descriptor() ([]byte, []int) {
	return file_drill_exercise_1_division_protobuf_div_proto_rawDescGZIP(), []int{0}
}

func (x *Number) GetFirst() int32 {
	if x != nil {
		return x.First
	}
	return 0
}

func (x *Number) GetSecond() int32 {
	if x != nil {
		return x.Second
	}
	return 0
}

type DivRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number *Number `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *DivRequest) Reset() {
	*x = DivRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_drill_exercise_1_division_protobuf_div_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DivRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DivRequest) ProtoMessage() {}

func (x *DivRequest) ProtoReflect() protoreflect.Message {
	mi := &file_drill_exercise_1_division_protobuf_div_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DivRequest.ProtoReflect.Descriptor instead.
func (*DivRequest) Descriptor() ([]byte, []int) {
	return file_drill_exercise_1_division_protobuf_div_proto_rawDescGZIP(), []int{1}
}

func (x *DivRequest) GetNumber() *Number {
	if x != nil {
		return x.Number
	}
	return nil
}

type DivResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *DivResponse) Reset() {
	*x = DivResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_drill_exercise_1_division_protobuf_div_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DivResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DivResponse) ProtoMessage() {}

func (x *DivResponse) ProtoReflect() protoreflect.Message {
	mi := &file_drill_exercise_1_division_protobuf_div_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DivResponse.ProtoReflect.Descriptor instead.
func (*DivResponse) Descriptor() ([]byte, []int) {
	return file_drill_exercise_1_division_protobuf_div_proto_rawDescGZIP(), []int{2}
}

func (x *DivResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_drill_exercise_1_division_protobuf_div_proto protoreflect.FileDescriptor

var file_drill_exercise_1_division_protobuf_div_proto_rawDesc = []byte{
	0x0a, 0x2c, 0x64, 0x72, 0x69, 0x6c, 0x6c, 0x5f, 0x65, 0x78, 0x65, 0x72, 0x63, 0x69, 0x73, 0x65,
	0x5f, 0x31, 0x2f, 0x64, 0x69, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x69, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03,
	0x64, 0x69, 0x76, 0x22, 0x36, 0x0a, 0x06, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x14, 0x0a,
	0x05, 0x66, 0x69, 0x72, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x66, 0x69,
	0x72, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x22, 0x31, 0x0a, 0x0a, 0x44,
	0x69, 0x76, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x06, 0x6e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x64, 0x69, 0x76, 0x2e,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x25,
	0x0a, 0x0b, 0x44, 0x69, 0x76, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0x34, 0x0a, 0x03, 0x44, 0x69, 0x76, 0x12, 0x2d, 0x0a, 0x08,
	0x44, 0x69, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x0f, 0x2e, 0x64, 0x69, 0x76, 0x2e, 0x44,
	0x69, 0x76, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x64, 0x69, 0x76, 0x2e,
	0x44, 0x69, 0x76, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2a, 0x5a, 0x28, 0x64,
	0x72, 0x69, 0x6c, 0x6c, 0x5f, 0x65, 0x78, 0x65, 0x72, 0x63, 0x69, 0x73, 0x65, 0x5f, 0x31, 0x2f,
	0x64, 0x69, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x3b, 0x64, 0x69, 0x76, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_drill_exercise_1_division_protobuf_div_proto_rawDescOnce sync.Once
	file_drill_exercise_1_division_protobuf_div_proto_rawDescData = file_drill_exercise_1_division_protobuf_div_proto_rawDesc
)

func file_drill_exercise_1_division_protobuf_div_proto_rawDescGZIP() []byte {
	file_drill_exercise_1_division_protobuf_div_proto_rawDescOnce.Do(func() {
		file_drill_exercise_1_division_protobuf_div_proto_rawDescData = protoimpl.X.CompressGZIP(file_drill_exercise_1_division_protobuf_div_proto_rawDescData)
	})
	return file_drill_exercise_1_division_protobuf_div_proto_rawDescData
}

var file_drill_exercise_1_division_protobuf_div_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_drill_exercise_1_division_protobuf_div_proto_goTypes = []interface{}{
	(*Number)(nil),      // 0: div.Number
	(*DivRequest)(nil),  // 1: div.DivRequest
	(*DivResponse)(nil), // 2: div.DivResponse
}
var file_drill_exercise_1_division_protobuf_div_proto_depIdxs = []int32{
	0, // 0: div.DivRequest.number:type_name -> div.Number
	1, // 1: div.Div.Division:input_type -> div.DivRequest
	2, // 2: div.Div.Division:output_type -> div.DivResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_drill_exercise_1_division_protobuf_div_proto_init() }
func file_drill_exercise_1_division_protobuf_div_proto_init() {
	if File_drill_exercise_1_division_protobuf_div_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_drill_exercise_1_division_protobuf_div_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Number); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_drill_exercise_1_division_protobuf_div_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DivRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_drill_exercise_1_division_protobuf_div_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DivResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_drill_exercise_1_division_protobuf_div_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_drill_exercise_1_division_protobuf_div_proto_goTypes,
		DependencyIndexes: file_drill_exercise_1_division_protobuf_div_proto_depIdxs,
		MessageInfos:      file_drill_exercise_1_division_protobuf_div_proto_msgTypes,
	}.Build()
	File_drill_exercise_1_division_protobuf_div_proto = out.File
	file_drill_exercise_1_division_protobuf_div_proto_rawDesc = nil
	file_drill_exercise_1_division_protobuf_div_proto_goTypes = nil
	file_drill_exercise_1_division_protobuf_div_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DivClient is the client API for Div service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DivClient interface {
	Division(ctx context.Context, in *DivRequest, opts ...grpc.CallOption) (*DivResponse, error)
}

type divClient struct {
	cc grpc.ClientConnInterface
}

func NewDivClient(cc grpc.ClientConnInterface) DivClient {
	return &divClient{cc}
}

func (c *divClient) Division(ctx context.Context, in *DivRequest, opts ...grpc.CallOption) (*DivResponse, error) {
	out := new(DivResponse)
	err := c.cc.Invoke(ctx, "/div.Div/Division", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DivServer is the server API for Div service.
type DivServer interface {
	Division(context.Context, *DivRequest) (*DivResponse, error)
}

// UnimplementedDivServer can be embedded to have forward compatible implementations.
type UnimplementedDivServer struct {
}

func (*UnimplementedDivServer) Division(context.Context, *DivRequest) (*DivResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Division not implemented")
}

func RegisterDivServer(s *grpc.Server, srv DivServer) {
	s.RegisterService(&_Div_serviceDesc, srv)
}

func _Div_Division_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DivRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DivServer).Division(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/div.Div/Division",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DivServer).Division(ctx, req.(*DivRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Div_serviceDesc = grpc.ServiceDesc{
	ServiceName: "div.Div",
	HandlerType: (*DivServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Division",
			Handler:    _Div_Division_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "drill_exercise_1/division/protobuf/div.proto",
}
