// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0-devel
// 	protoc        v3.12.3
// source: exercise/multiplication/protobuf/multi.proto

package multipb

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Number struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	First  int32 `protobuf:"varint,1,opt,name=first,proto3" json:"first,omitempty"`
	Second int32 `protobuf:"varint,2,opt,name=second,proto3" json:"second,omitempty"`
}

func (x *Number) Reset() {
	*x = Number{}
	if protoimpl.UnsafeEnabled {
		mi := &file_exercise_multiplication_protobuf_multi_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Number) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Number) ProtoMessage() {}

func (x *Number) ProtoReflect() protoreflect.Message {
	mi := &file_exercise_multiplication_protobuf_multi_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Number.ProtoReflect.Descriptor instead.
func (*Number) Descriptor() ([]byte, []int) {
	return file_exercise_multiplication_protobuf_multi_proto_rawDescGZIP(), []int{0}
}

func (x *Number) GetFirst() int32 {
	if x != nil {
		return x.First
	}
	return 0
}

func (x *Number) GetSecond() int32 {
	if x != nil {
		return x.Second
	}
	return 0
}

type MultiRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num *Number `protobuf:"bytes,1,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *MultiRequest) Reset() {
	*x = MultiRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_exercise_multiplication_protobuf_multi_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiRequest) ProtoMessage() {}

func (x *MultiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exercise_multiplication_protobuf_multi_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiRequest.ProtoReflect.Descriptor instead.
func (*MultiRequest) Descriptor() ([]byte, []int) {
	return file_exercise_multiplication_protobuf_multi_proto_rawDescGZIP(), []int{1}
}

func (x *MultiRequest) GetNum() *Number {
	if x != nil {
		return x.Num
	}
	return nil
}

type MultiResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *MultiResponse) Reset() {
	*x = MultiResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_exercise_multiplication_protobuf_multi_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiResponse) ProtoMessage() {}

func (x *MultiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_exercise_multiplication_protobuf_multi_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiResponse.ProtoReflect.Descriptor instead.
func (*MultiResponse) Descriptor() ([]byte, []int) {
	return file_exercise_multiplication_protobuf_multi_proto_rawDescGZIP(), []int{2}
}

func (x *MultiResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_exercise_multiplication_protobuf_multi_proto protoreflect.FileDescriptor

var file_exercise_multiplication_protobuf_multi_proto_rawDesc = []byte{
	0x0a, 0x2c, 0x65, 0x78, 0x65, 0x72, 0x63, 0x69, 0x73, 0x65, 0x2f, 0x6d, 0x75, 0x6c, 0x74, 0x69,
	0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05,
	0x6d, 0x75, 0x6c, 0x74, 0x69, 0x22, 0x36, 0x0a, 0x06, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12,
	0x14, 0x0a, 0x05, 0x66, 0x69, 0x72, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x66, 0x69, 0x72, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x22, 0x2f, 0x0a,
	0x0c, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a,
	0x03, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x75, 0x6c,
	0x74, 0x69, 0x2e, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x22, 0x27,
	0x0a, 0x0d, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0x4b, 0x0a, 0x0c, 0x4d, 0x75, 0x6c, 0x74, 0x69,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3b, 0x0a, 0x0e, 0x4d, 0x75, 0x6c, 0x74, 0x69,
	0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x13, 0x2e, 0x6d, 0x75, 0x6c, 0x74,
	0x69, 0x2e, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14,
	0x2e, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x2e, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2a, 0x5a, 0x28, 0x65, 0x78, 0x65, 0x72, 0x63, 0x69, 0x73, 0x65,
	0x2f, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x3b, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_exercise_multiplication_protobuf_multi_proto_rawDescOnce sync.Once
	file_exercise_multiplication_protobuf_multi_proto_rawDescData = file_exercise_multiplication_protobuf_multi_proto_rawDesc
)

func file_exercise_multiplication_protobuf_multi_proto_rawDescGZIP() []byte {
	file_exercise_multiplication_protobuf_multi_proto_rawDescOnce.Do(func() {
		file_exercise_multiplication_protobuf_multi_proto_rawDescData = protoimpl.X.CompressGZIP(file_exercise_multiplication_protobuf_multi_proto_rawDescData)
	})
	return file_exercise_multiplication_protobuf_multi_proto_rawDescData
}

var file_exercise_multiplication_protobuf_multi_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_exercise_multiplication_protobuf_multi_proto_goTypes = []interface{}{
	(*Number)(nil),        // 0: multi.Number
	(*MultiRequest)(nil),  // 1: multi.MultiRequest
	(*MultiResponse)(nil), // 2: multi.MultiResponse
}
var file_exercise_multiplication_protobuf_multi_proto_depIdxs = []int32{
	0, // 0: multi.MultiRequest.num:type_name -> multi.Number
	1, // 1: multi.MultiService.Multiplication:input_type -> multi.MultiRequest
	2, // 2: multi.MultiService.Multiplication:output_type -> multi.MultiResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_exercise_multiplication_protobuf_multi_proto_init() }
func file_exercise_multiplication_protobuf_multi_proto_init() {
	if File_exercise_multiplication_protobuf_multi_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_exercise_multiplication_protobuf_multi_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Number); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_exercise_multiplication_protobuf_multi_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultiRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_exercise_multiplication_protobuf_multi_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultiResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_exercise_multiplication_protobuf_multi_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_exercise_multiplication_protobuf_multi_proto_goTypes,
		DependencyIndexes: file_exercise_multiplication_protobuf_multi_proto_depIdxs,
		MessageInfos:      file_exercise_multiplication_protobuf_multi_proto_msgTypes,
	}.Build()
	File_exercise_multiplication_protobuf_multi_proto = out.File
	file_exercise_multiplication_protobuf_multi_proto_rawDesc = nil
	file_exercise_multiplication_protobuf_multi_proto_goTypes = nil
	file_exercise_multiplication_protobuf_multi_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MultiServiceClient is the client API for MultiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MultiServiceClient interface {
	Multiplication(ctx context.Context, in *MultiRequest, opts ...grpc.CallOption) (*MultiResponse, error)
}

type multiServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMultiServiceClient(cc grpc.ClientConnInterface) MultiServiceClient {
	return &multiServiceClient{cc}
}

func (c *multiServiceClient) Multiplication(ctx context.Context, in *MultiRequest, opts ...grpc.CallOption) (*MultiResponse, error) {
	out := new(MultiResponse)
	err := c.cc.Invoke(ctx, "/multi.MultiService/Multiplication", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MultiServiceServer is the server API for MultiService service.
type MultiServiceServer interface {
	Multiplication(context.Context, *MultiRequest) (*MultiResponse, error)
}

// UnimplementedMultiServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMultiServiceServer struct {
}

func (*UnimplementedMultiServiceServer) Multiplication(context.Context, *MultiRequest) (*MultiResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Multiplication not implemented")
}

func RegisterMultiServiceServer(s *grpc.Server, srv MultiServiceServer) {
	s.RegisterService(&_MultiService_serviceDesc, srv)
}

func _MultiService_Multiplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MultiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultiServiceServer).Multiplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/multi.MultiService/Multiplication",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultiServiceServer).Multiplication(ctx, req.(*MultiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MultiService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "multi.MultiService",
	HandlerType: (*MultiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Multiplication",
			Handler:    _MultiService_Multiplication_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "exercise/multiplication/protobuf/multi.proto",
}
