// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0-devel
// 	protoc        v3.12.3
// source: exercise/substraction/protobuf/subs.proto

package substractpb

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Substraction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	First  int32 `protobuf:"varint,1,opt,name=first,proto3" json:"first,omitempty"`
	Second int32 `protobuf:"varint,2,opt,name=second,proto3" json:"second,omitempty"`
}

func (x *Substraction) Reset() {
	*x = Substraction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_exercise_substraction_protobuf_subs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Substraction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Substraction) ProtoMessage() {}

func (x *Substraction) ProtoReflect() protoreflect.Message {
	mi := &file_exercise_substraction_protobuf_subs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Substraction.ProtoReflect.Descriptor instead.
func (*Substraction) Descriptor() ([]byte, []int) {
	return file_exercise_substraction_protobuf_subs_proto_rawDescGZIP(), []int{0}
}

func (x *Substraction) GetFirst() int32 {
	if x != nil {
		return x.First
	}
	return 0
}

func (x *Substraction) GetSecond() int32 {
	if x != nil {
		return x.Second
	}
	return 0
}

type SubstractRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Substraction *Substraction `protobuf:"bytes,1,opt,name=substraction,proto3" json:"substraction,omitempty"`
}

func (x *SubstractRequest) Reset() {
	*x = SubstractRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_exercise_substraction_protobuf_subs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubstractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubstractRequest) ProtoMessage() {}

func (x *SubstractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exercise_substraction_protobuf_subs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubstractRequest.ProtoReflect.Descriptor instead.
func (*SubstractRequest) Descriptor() ([]byte, []int) {
	return file_exercise_substraction_protobuf_subs_proto_rawDescGZIP(), []int{1}
}

func (x *SubstractRequest) GetSubstraction() *Substraction {
	if x != nil {
		return x.Substraction
	}
	return nil
}

type SubstractResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *SubstractResponse) Reset() {
	*x = SubstractResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_exercise_substraction_protobuf_subs_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubstractResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubstractResponse) ProtoMessage() {}

func (x *SubstractResponse) ProtoReflect() protoreflect.Message {
	mi := &file_exercise_substraction_protobuf_subs_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubstractResponse.ProtoReflect.Descriptor instead.
func (*SubstractResponse) Descriptor() ([]byte, []int) {
	return file_exercise_substraction_protobuf_subs_proto_rawDescGZIP(), []int{2}
}

func (x *SubstractResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_exercise_substraction_protobuf_subs_proto protoreflect.FileDescriptor

var file_exercise_substraction_protobuf_subs_proto_rawDesc = []byte{
	0x0a, 0x29, 0x65, 0x78, 0x65, 0x72, 0x63, 0x69, 0x73, 0x65, 0x2f, 0x73, 0x75, 0x62, 0x73, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x73, 0x75, 0x62, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x73, 0x75, 0x62,
	0x73, 0x74, 0x72, 0x61, 0x63, 0x74, 0x22, 0x3c, 0x0a, 0x0c, 0x53, 0x75, 0x62, 0x73, 0x74, 0x72,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x69, 0x72, 0x73, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x66, 0x69, 0x72, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x65,
	0x63, 0x6f, 0x6e, 0x64, 0x22, 0x4f, 0x0a, 0x10, 0x53, 0x75, 0x62, 0x73, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3b, 0x0a, 0x0c, 0x73, 0x75, 0x62, 0x73,
	0x74, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17,
	0x2e, 0x73, 0x75, 0x62, 0x73, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0c, 0x73, 0x75, 0x62, 0x73, 0x74, 0x72, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x2b, 0x0a, 0x11, 0x53, 0x75, 0x62, 0x73, 0x74, 0x72, 0x61,
	0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x32, 0x5a, 0x0a, 0x10, 0x53, 0x75, 0x62, 0x73, 0x74, 0x72, 0x61, 0x63, 0x74, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x46, 0x0a, 0x09, 0x53, 0x75, 0x62, 0x73, 0x74, 0x72,
	0x61, 0x63, 0x74, 0x12, 0x1b, 0x2e, 0x73, 0x75, 0x62, 0x73, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e,
	0x53, 0x75, 0x62, 0x73, 0x74, 0x72, 0x61, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1c, 0x2e, 0x73, 0x75, 0x62, 0x73, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x53, 0x75, 0x62,
	0x73, 0x74, 0x72, 0x61, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2c,
	0x5a, 0x2a, 0x65, 0x78, 0x65, 0x72, 0x63, 0x69, 0x73, 0x65, 0x2f, 0x73, 0x75, 0x62, 0x73, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x3b, 0x73, 0x75, 0x62, 0x73, 0x74, 0x72, 0x61, 0x63, 0x74, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_exercise_substraction_protobuf_subs_proto_rawDescOnce sync.Once
	file_exercise_substraction_protobuf_subs_proto_rawDescData = file_exercise_substraction_protobuf_subs_proto_rawDesc
)

func file_exercise_substraction_protobuf_subs_proto_rawDescGZIP() []byte {
	file_exercise_substraction_protobuf_subs_proto_rawDescOnce.Do(func() {
		file_exercise_substraction_protobuf_subs_proto_rawDescData = protoimpl.X.CompressGZIP(file_exercise_substraction_protobuf_subs_proto_rawDescData)
	})
	return file_exercise_substraction_protobuf_subs_proto_rawDescData
}

var file_exercise_substraction_protobuf_subs_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_exercise_substraction_protobuf_subs_proto_goTypes = []interface{}{
	(*Substraction)(nil),      // 0: substract.Substraction
	(*SubstractRequest)(nil),  // 1: substract.SubstractRequest
	(*SubstractResponse)(nil), // 2: substract.SubstractResponse
}
var file_exercise_substraction_protobuf_subs_proto_depIdxs = []int32{
	0, // 0: substract.SubstractRequest.substraction:type_name -> substract.Substraction
	1, // 1: substract.SubstractService.Substract:input_type -> substract.SubstractRequest
	2, // 2: substract.SubstractService.Substract:output_type -> substract.SubstractResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_exercise_substraction_protobuf_subs_proto_init() }
func file_exercise_substraction_protobuf_subs_proto_init() {
	if File_exercise_substraction_protobuf_subs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_exercise_substraction_protobuf_subs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Substraction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_exercise_substraction_protobuf_subs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubstractRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_exercise_substraction_protobuf_subs_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubstractResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_exercise_substraction_protobuf_subs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_exercise_substraction_protobuf_subs_proto_goTypes,
		DependencyIndexes: file_exercise_substraction_protobuf_subs_proto_depIdxs,
		MessageInfos:      file_exercise_substraction_protobuf_subs_proto_msgTypes,
	}.Build()
	File_exercise_substraction_protobuf_subs_proto = out.File
	file_exercise_substraction_protobuf_subs_proto_rawDesc = nil
	file_exercise_substraction_protobuf_subs_proto_goTypes = nil
	file_exercise_substraction_protobuf_subs_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SubstractServiceClient is the client API for SubstractService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SubstractServiceClient interface {
	Substract(ctx context.Context, in *SubstractRequest, opts ...grpc.CallOption) (*SubstractResponse, error)
}

type substractServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSubstractServiceClient(cc grpc.ClientConnInterface) SubstractServiceClient {
	return &substractServiceClient{cc}
}

func (c *substractServiceClient) Substract(ctx context.Context, in *SubstractRequest, opts ...grpc.CallOption) (*SubstractResponse, error) {
	out := new(SubstractResponse)
	err := c.cc.Invoke(ctx, "/substract.SubstractService/Substract", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SubstractServiceServer is the server API for SubstractService service.
type SubstractServiceServer interface {
	Substract(context.Context, *SubstractRequest) (*SubstractResponse, error)
}

// UnimplementedSubstractServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSubstractServiceServer struct {
}

func (*UnimplementedSubstractServiceServer) Substract(context.Context, *SubstractRequest) (*SubstractResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Substract not implemented")
}

func RegisterSubstractServiceServer(s *grpc.Server, srv SubstractServiceServer) {
	s.RegisterService(&_SubstractService_serviceDesc, srv)
}

func _SubstractService_Substract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubstractRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubstractServiceServer).Substract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/substract.SubstractService/Substract",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubstractServiceServer).Substract(ctx, req.(*SubstractRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SubstractService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "substract.SubstractService",
	HandlerType: (*SubstractServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Substract",
			Handler:    _SubstractService_Substract_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "exercise/substraction/protobuf/subs.proto",
}
